### ISSUE TITLE
The solution for Cannot open file "gdi32.lib"

### ISSUE THREAD

**Issue by htw128** [AlexGuo1998/BeepPlayer#1]
编译的时候提示无法打开gdi32.lib 
如果像我一样刚刚接触这个圈子，或者升级了最新的Windows 10 15063，则需要在VS里单独安装相对应的Windows 10 SDK.

**Comment by AlexGuo1998** [comment]
并不需要gdi32.lib

**Comment by htw128** [comment]
需要的？我安装完了之后就解决了。

**Comment by AlexGuo1998** [comment]
那可能不是gdi32.lib的问题，是因为你没安装Windows SDK。编译任何一个Windows程序时都会默认链接一些库，都会出错。
