### ISSUE TITLE
闪退啊……

### ISSUE THREAD

**Issue by htw128** [AlexGuo1998/BeepPlayer#2]
以下是调试信息……我对这方面一点都不懂……还请大佬看啊可能是怎么回事了
`beepplayer.exe”(Win32): 已加载“C:\Users\tiger\Downloads\BeepPlayer-master\BeepPlayer-master\beepplayer\x64\Debug\beepplayer.exe”。已加载符号。
“beepplayer.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。无法查找或打开 PDB 文件。
“beepplayer.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。无法查找或打开 PDB 文件。
“beepplayer.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。无法查找或打开 PDB 文件。
“beepplayer.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140d.dll”。无法查找或打开 PDB 文件。
“beepplayer.exe”(Win32): 已加载“C:\Windows\System32\ucrtbased.dll”。无法查找或打开 PDB 文件。
“beepplayer.exe”(Win32): 已加载“C:\Windows\System32\ucrtbased.dll”。无法查找或打开 PDB 文件。
“beepplayer.exe”(Win32): 已卸载“C:\Windows\System32\ucrtbased.dll”
“beepplayer.exe”(Win32): 已加载“C:\Windows\System32\kernel.appcore.dll”。无法查找或打开 PDB 文件。
“beepplayer.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。无法查找或打开 PDB 文件。
“beepplayer.exe”(Win32): 已加载“C:\Windows\System32\rpcrt4.dll”。无法查找或打开 PDB 文件。
线程 0x14f8 已退出，返回值为 1 (0x1)。
线程 0x1ac4 已退出，返回值为 1 (0x1)。
线程 0x2ad8 已退出，返回值为 1 (0x1)。
程序“[9888] beepplayer.exe”已退出，返回值为 1 (0x1)。`

**Comment by AlexGuo1998** [comment]
正常状况。
请在命令行中执行，不带参数执行时会打印帮助信息并且直接退出。
