### ISSUE TITLE
不能从crontab运行

### ISSUE THREAD

**Issue by maidmeow4** [AlexGuo1998/BeepPlayer#4]
在Linux下不能从crontab定时运行beepplayer，系统是Fedora 35

**Comment by AlexGuo1998** [comment]
[如何有效地报告 Bug](https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html)

**Comment by maidmeow4** [comment]
从crontab无论直接调用beepplayer还是通过bash脚本调用beepplayer，都不能定时使 PC speaker发出声音，crontab是root身份的
比如这样 `*/1 * * * * /usr/local/bin/make-noise.sh` 或是 `*/1 * * * * beepplayer /usr/local/share/noise.txt`
直接在命令行运行 `beepplayer /usr/local/share/noise.txt` 或是 `/usr/local/bin/make-noise.sh` 是正常的

**Comment by maidmeow4** [comment]
Solved, need to use absolute path to run beepplayer.
